### ISSUE TITLE
Shareloc detection failed

### ISSUE THREAD

**Issue by baiddd** [imodpasteur/shareloc-collection#38]
Dear @oeway,
Since 5 days ago we have [issues](https://github.com/imodpasteur/shareloc-collection/actions/runs/3653323443/jobs/6172661123#step:4:1) with pip install pypotree, I tried locally but didn't work either (but on [Colab](https://colab.research.google.com/drive/1It3EbWy9W8Xf65ikP-_tpkVdJRmvwTQT#scrollTo=uzsS0deEsPTv) it works), could you please take a closer look?
Thanks,

**Comment by oeway** [comment]
Hi, I found the issue in the error log:

> DEPRECATION: pypotree is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559


It should have been fixed now: https://github.com/imodpasteur/shareloc-collection/commit/f2ff720cc6447b707ad2ec3e1580cfc0be0bb0c1

**Comment by baiddd** [comment]
seems didn't work :( like [here](https://github.com/imodpasteur/shareloc-collection/actions/runs/3712957683)

**Comment by oeway** [comment]
@baiddd Fixed now, because the ubuntu version was upgraded to 22.04, and I had to pin it to 20.04 to make it work: https://github.com/imodpasteur/shareloc-collection/commit/727aeaf0dc5208990688cbe9d9103655f4a23dd0

https://github.com/imodpasteur/shareloc-collection/actions/runs/3736177143/jobs/6340203815
